#pragma once

////////////////////////////////////////////////////////////////////////////////
// This source file is autogenerated. Do not edit it directly
////////////////////////////////////////////////////////////////////////////////

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

struct Error {

    int code;

    std::string message;
};

struct Pet {

    int id;

    std::string name;

    std::optional<std::string> tag;
};

using Pets = std::vector<Pet>;
