name: Build openapi-yagen
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./build-musl.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-yagen
          path: dist/openapi-yagen

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/openapi-yagen
